/**
 * Copyright (c) VA360 LABS S.L.
 * SPDX-License-Identifier: LicenseRef-Didacta-Sustainable-Use
 */

import { apiFetch } from './api-client';
import { tenantSettingsApi } from './tenant-settings';

/** Identidad de la academia de quien llama. Ver `AdminAcademyController`. */
export interface Academy {
  name: string;
  slug: string;
  primaryHostname: string | null;
  /** El nombre sigue siendo el deducido al comprar (del correo, típicamente). */
  looksAutogenerated: boolean;
}

export const academyApi = {
  async getMine(bearer: string): Promise<Academy> {
    return apiFetch<Academy>('/api/v1/admin/tenant-settings/academy', { method: 'GET' }, bearer);
  },
  async rename(bearer: string, name: string): Promise<Academy> {
    return apiFetch<Academy>(
      '/api/v1/admin/tenant-settings/academy',
      { method: 'PUT', body: JSON.stringify({ name }) },
      bearer,
    );
  },
};

/**
 * Los pasos del asistente, en el orden en que se recorren.
 *
 * `direccion` ya no es un paso: era una pantalla puramente informativa y su
 * contenido (la URL del aula + copiar + dominio propio) vive ahora en el
 * resumen. `normalizar()` absorbe el cambio para progresos guardados con el
 * paso viejo: un `step` desconocido cae a `bienvenida` y las entradas
 * desconocidas de `done`/`skipped` se filtran.
 */
export const ONBOARDING_STEPS = [
  'bienvenida',
  'nombre',
  'marca',
  'curso',
  'alumnos',
  'cobros',
  'correo',
  'resumen',
] as const;

/** Pasos que cuentan para el «Paso X de N» (todos menos portada y resumen). */
export const PASOS_CONTABLES = ONBOARDING_STEPS.length - 2;

export type OnboardingStep = (typeof ONBOARDING_STEPS)[number];

/**
 * Adónde llevan los pasos que se resuelven en otra pantalla del panel, y los
 * pendientes del resumen. Vive aquí (no en la página) para que un test pueda
 * afirmar que cada destino es una RUTA QUE EXISTE: el primer asistente enlazaba
 * `/admin/cursos` (nunca existió) y `/admin/billing` (tampoco), y ambos 404
 * llegaron a producción porque nada los comprobaba.
 *
 * - `cobros`: la cuenta de Stripe del tenant se pega en Configuración →
 *   pestaña «Pagos» (`StripeSettingsCard`). `/admin/billing/products` es el
 *   paso SIGUIENTE (vincular cursos a precios), no el primero.
 * - `correo`: enviar con remitente propio es el SMTP de Configuración →
 *   «Notificaciones». `/admin/emails` son las plantillas, otra cosa.
 */
export const DESTINOS: Partial<Record<OnboardingStep, string>> = {
  curso: '/formador/cursos',
  alumnos: '/admin/usuarios/invitar',
  cobros: '/admin/configuracion?tab=pagos',
  correo: '/admin/configuracion?tab=notifications',
};

/**
 * El pase del asistente.
 *
 * El gate del shell autenticado manda a todo admin con el asistente sin
 * completar a `/bienvenida` — es lo que lo hace bloqueante. Pero los enlaces
 * DEL PROPIO asistente («Abrir la configuración de cobros», el editor del
 * curso, los pendientes del resumen) abren pestaña nueva… que pasa por ese
 * mismo gate y volvía rebotada al asistente: sus enlaces eran imposibles de
 * usar. En producción se vio como «configurar el correo me llevó a "Listo"».
 *
 * El pase vive en localStorage (compartido entre pestañas, a diferencia de
 * sessionStorage) y caduca solo: media hora cubre de sobra configurar Stripe
 * o el SMTP sin dejar la puerta abierta para siempre. Completar el asistente
 * lo retira.
 */
const PASE_KEY = 'didacta.bienvenida.pase';
const PASE_TTL_MS = 30 * 60 * 1000;

export function concederPaseDeBienvenida(): void {
  if (typeof window === 'undefined') return;
  try {
    localStorage.setItem(PASE_KEY, String(Date.now()));
  } catch {
    // Sin localStorage el enlace rebotará al asistente: peor UX, no un fallo.
  }
}

export function retirarPaseDeBienvenida(): void {
  if (typeof window === 'undefined') return;
  try {
    localStorage.removeItem(PASE_KEY);
  } catch {
    // Ídem.
  }
}

export function hayPaseDeBienvenida(): boolean {
  if (typeof window === 'undefined') return false;
  try {
    const ts = Number(localStorage.getItem(PASE_KEY));
    return Number.isFinite(ts) && ts > 0 && Date.now() - ts < PASE_TTL_MS;
  } catch {
    return false;
  }
}

/**
 * Los pasos que NO se pueden saltar.
 *
 * Decisión de producto: el asistente es bloqueante, pero sólo se exige lo que
 * deja la academia reconocible como suya. Invitar alumnos, crear el primer
 * curso, cobrar y configurar el correo son cosas legítimas de «ahora no»: una
 * academia que aún no tiene alumnos no debería quedar atrapada aquí.
 */
export const PASOS_OBLIGATORIOS: readonly OnboardingStep[] = ['nombre', 'marca'];

export interface OnboardingProgress {
  /** Último paso en el que estaba, para volver donde lo dejó. */
  step: OnboardingStep;
  /** Pasos resueltos, ya sea completándolos o saltándolos. */
  done: OnboardingStep[];
  /** Pasos que dijo «ahora no». Se listan en el resumen como pendientes. */
  skipped: OnboardingStep[];
  /** Timestamp ISO. Mientras sea null, el asistente sigue apareciendo. */
  completedAt: string | null;
}

const SCOPE = 'onboarding';
const KEY = 'academy';

export const VACIO: OnboardingProgress = {
  step: 'bienvenida',
  done: [],
  skipped: [],
  completedAt: null,
};

function normalizar(raw: unknown): OnboardingProgress {
  if (!raw || typeof raw !== 'object') return VACIO;
  const o = raw as Partial<OnboardingProgress>;
  const pasos = new Set<string>(ONBOARDING_STEPS);
  const limpiar = (xs: unknown): OnboardingStep[] =>
    Array.isArray(xs)
      ? (xs.filter((x) => typeof x === 'string' && pasos.has(x)) as OnboardingStep[])
      : [];
  return {
    step:
      typeof o.step === 'string' && pasos.has(o.step) ? (o.step as OnboardingStep) : 'bienvenida',
    done: limpiar(o.done),
    skipped: limpiar(o.skipped),
    completedAt: typeof o.completedAt === 'string' ? o.completedAt : null,
  };
}

/**
 * El progreso vive en el servidor (`tenant_setting`), no en el navegador.
 *
 * Dos razones: si cierra el portátil a mitad, al volver sigue donde estaba
 * aunque entre desde otro sitio; y si la academia tiene dos administradores,
 * el segundo no se encuentra el asistente otra vez porque el primero ya lo
 * hizo. Es estado de la academia, no de la sesión.
 */
export const onboardingApi = {
  async read(): Promise<OnboardingProgress> {
    try {
      const detail = await tenantSettingsApi.get(SCOPE, KEY);
      return normalizar(detail.value);
    } catch {
      // 404 la primera vez, y cualquier otro fallo: se empieza de cero. Nunca
      // se bloquea al admin por no poder leer el progreso.
      return VACIO;
    }
  },
  async write(progress: OnboardingProgress): Promise<void> {
    await tenantSettingsApi.upsert(SCOPE, KEY, { value: progress });
  },
};
