/**
 * Copyright (c) VA360 LABS S.L.
 * SPDX-License-Identifier: LicenseRef-Didacta-Sustainable-Use
 */

/**
 * Checklist «Primeros pasos» del panel (lote de feedback de onboarding).
 *
 * Derivado de DATOS REALES, no de un estado propio que se desincronice: cada
 * ítem se calcula de la fuente que ya sabe la verdad (identidad de la
 * academia, theme, SMTP, Stripe) y solo curso/alumnos se leen del progreso
 * del asistente — su señal barata. Una entrada cuya fuente no se pudo leer
 * se OMITE en vez de inventarse un estado.
 *
 * La visibilidad es cosa del componente (solo admins, solo con el asistente
 * completado, descartable); aquí vive la derivación pura para poder fijarla
 * con tests.
 */

import type { Academy, OnboardingProgress } from './academy';
import { DESTINOS } from './academy';
import type { AdminSmtpStatus } from './admin-smtp';
import type { TenantTheme } from './theming';

export type ChecklistItemKey = 'nombre' | 'marca' | 'curso' | 'alumnos' | 'cobros' | 'correo';

export interface ChecklistItem {
  key: ChecklistItemKey;
  done: boolean;
  /** Adónde ir a resolverlo. Reusa DESTINOS del asistente (rutas testeadas). */
  href: string;
}

export interface ChecklistInputs {
  /** null = no se pudo leer esa fuente (el ítem se omite). */
  academy: Academy | null;
  theme: TenantTheme | null;
  smtpStatus: AdminSmtpStatus | null;
  /** `hasSecretKey` del DTO de Stripe. */
  stripeConfigured: boolean | null;
  progress: OnboardingProgress | null;
}

/**
 * Un paso del asistente cuenta como hecho solo si está en `done` Y no en
 * `skipped`. En el asistente actual son excluyentes (marcar uno borra el
 * otro, ver `irA` en bienvenida/page.tsx); el doble chequeo es cinturón y
 * tirantes frente a progresos guardados por versiones con otra semántica —
 * ante la duda, reclamar el paso es el fallo barato.
 */
function pasoHecho(progress: OnboardingProgress, paso: 'curso' | 'alumnos' | 'cobros'): boolean {
  return progress.done.includes(paso) && !progress.skipped.includes(paso);
}

/**
 * ¿El admin respondió «No vendo cursos» en el paso de cobros del asistente?
 *
 * La señal es inequívoca: ese botón marca `cobros` como hecho SIN configurar
 * Stripe — el único otro camino a `done` es guardar la config, y entonces
 * `hasSecretKey` es true. «Ahora no» (skipped) es distinto: eso es «luego»,
 * y el checklist sí debe reclamarlo.
 */
function dijoQueNoVende(inputs: ChecklistInputs): boolean {
  return (
    inputs.progress !== null &&
    pasoHecho(inputs.progress, 'cobros') &&
    inputs.stripeConfigured === false
  );
}

export function deriveChecklist(inputs: ChecklistInputs): ChecklistItem[] {
  const items: ChecklistItem[] = [];
  if (inputs.academy) {
    items.push({
      key: 'nombre',
      done: !inputs.academy.looksAutogenerated,
      href: '/admin/configuracion',
    });
  }
  if (inputs.theme) {
    items.push({ key: 'marca', done: inputs.theme.logoUrl !== null, href: '/admin/branding' });
  }
  if (inputs.progress) {
    items.push({ key: 'curso', done: pasoHecho(inputs.progress, 'curso'), href: DESTINOS.curso! });
    items.push({
      key: 'alumnos',
      done: pasoHecho(inputs.progress, 'alumnos'),
      href: DESTINOS.alumnos!,
    });
  }
  // Quien respondió «No vendo cursos» en el asistente no tiene un pendiente
  // de Stripe: tiene una decisión tomada. El ítem se OMITE — pintarlo como
  // hecho sería mentir y dejarlo pendiente sería reclamar eternamente algo
  // que dijo que no quiere (feedback de Valen, 15-ago).
  if (inputs.stripeConfigured !== null && !dijoQueNoVende(inputs)) {
    items.push({ key: 'cobros', done: inputs.stripeConfigured, href: DESTINOS.cobros! });
  }
  if (inputs.smtpStatus !== null) {
    // `fallback` cuenta como hecho: el correo SALE (por el SMTP global del
    // despliegue). Reclamar aquí sería contradecir al banner del shell, que
    // solo avisa en `none` por el mismo motivo.
    items.push({ key: 'correo', done: inputs.smtpStatus !== 'none', href: DESTINOS.correo! });
  }
  return items;
}

export function isChecklistComplete(items: ChecklistItem[]): boolean {
  return items.length > 0 && items.every((i) => i.done);
}

/**
 * Descarte de la tarjeta, por navegador y tenant (localStorage). Deliberado
 * que NO sea estado de la academia: ocultarse la tarjeta es una preferencia
 * de quien la mira, no una decisión del tenant — otro admin puede seguir
 * queriéndola.
 */
const DISMISS_KEY = 'didacta.primeros-pasos.v1';

export function checklistDismissed(tenantId: string): boolean {
  if (typeof window === 'undefined') return false;
  try {
    return localStorage.getItem(`${DISMISS_KEY}.${tenantId}`) !== null;
  } catch {
    return false;
  }
}

export function dismissChecklist(tenantId: string): void {
  if (typeof window === 'undefined') return;
  try {
    localStorage.setItem(`${DISMISS_KEY}.${tenantId}`, String(Date.now()));
  } catch {
    // Sin localStorage la tarjeta reaparece en la próxima visita: molesto,
    // no un fallo.
  }
}
