import { describe, expect, it } from 'vitest';
import type { OnboardingProgress } from './academy';
import { deriveChecklist, isChecklistComplete, type ChecklistInputs } from './getting-started';

const PROGRESO_TODO_HECHO: OnboardingProgress = {
  step: 'resumen',
  done: ['nombre', 'marca', 'curso', 'alumnos', 'cobros', 'correo'],
  skipped: [],
  completedAt: '2026-08-15T10:00:00.000Z',
};

function inputs(overrides: Partial<ChecklistInputs> = {}): ChecklistInputs {
  return {
    academy: {
      name: 'Academia Real',
      slug: 'academia-real',
      primaryHostname: null,
      looksAutogenerated: false,
    },
    theme: { logoUrl: '/api/v1/modules/theming/tenants/t1/logo?v=1' } as never,
    smtpStatus: 'verified',
    stripeConfigured: true,
    progress: PROGRESO_TODO_HECHO,
    ...overrides,
  };
}

describe('deriveChecklist', () => {
  it('con todas las fuentes sanas produce los 6 ítems, todos hechos', () => {
    const items = deriveChecklist(inputs());
    expect(items).toHaveLength(6);
    expect(items.every((i) => i.done)).toBe(true);
    expect(isChecklistComplete(items)).toBe(true);
  });

  it('cada ítem refleja SU fuente real, no el estado del asistente', () => {
    const items = deriveChecklist(
      inputs({
        academy: {
          name: 'valen.ayesa',
          slug: 'x',
          primaryHostname: null,
          looksAutogenerated: true,
        },
        theme: { logoUrl: null } as never,
        smtpStatus: 'none',
        stripeConfigured: false,
        // Cobros SALTADO («Ahora no»), no respondido con «No vendo cursos»:
        // el ítem debe reclamarse.
        progress: { ...PROGRESO_TODO_HECHO, done: ['curso', 'alumnos'], skipped: ['cobros'] },
      }),
    );
    const byKey = Object.fromEntries(items.map((i) => [i.key, i.done]));
    expect(byKey['nombre']).toBe(false);
    expect(byKey['marca']).toBe(false);
    expect(byKey['correo']).toBe(false);
    expect(byKey['cobros']).toBe(false);
    // curso/alumnos vienen del progreso.
    expect(byKey['curso']).toBe(true);
    expect(byKey['alumnos']).toBe(true);
  });

  it('«No vendo cursos» (cobros hecho en el asistente SIN Stripe) omite el ítem de cobros', () => {
    const items = deriveChecklist(inputs({ stripeConfigured: false }));
    // PROGRESO_TODO_HECHO lleva cobros en done: esa combinación solo sale del
    // botón «No vendo cursos», así que no hay pendiente que reclamar.
    expect(items.find((i) => i.key === 'cobros')).toBeUndefined();
    expect(items).toHaveLength(5);
  });

  it('con Stripe configurado el ítem se enseña hecho, diga lo que diga el asistente', () => {
    const items = deriveChecklist(
      inputs({
        stripeConfigured: true,
        progress: { ...PROGRESO_TODO_HECHO, done: ['curso', 'alumnos'], skipped: ['cobros'] },
      }),
    );
    expect(items.find((i) => i.key === 'cobros')?.done).toBe(true);
  });

  it('un paso saltado en el asistente («Ahora no») queda pendiente', () => {
    const items = deriveChecklist(
      inputs({
        progress: {
          ...PROGRESO_TODO_HECHO,
          done: ['nombre', 'marca', 'curso'],
          skipped: ['alumnos', 'cobros', 'correo'],
        },
      }),
    );
    const byKey = Object.fromEntries(items.map((i) => [i.key, i.done]));
    expect(byKey['curso']).toBe(true);
    expect(byKey['alumnos']).toBe(false);
  });

  it('el SMTP en fallback global cuenta como hecho (el correo sale; misma regla que el banner)', () => {
    const items = deriveChecklist(inputs({ smtpStatus: 'fallback' }));
    expect(items.find((i) => i.key === 'correo')?.done).toBe(true);
  });

  it('una fuente ilegible omite su ítem en vez de inventar un estado', () => {
    const items = deriveChecklist(
      inputs({ academy: null, theme: null, smtpStatus: null, stripeConfigured: null }),
    );
    expect(items.map((i) => i.key)).toEqual(['curso', 'alumnos']);
  });

  it('sin progreso no hay ítems de curso/alumnos', () => {
    const items = deriveChecklist(inputs({ progress: null }));
    expect(items.map((i) => i.key)).toEqual(['nombre', 'marca', 'cobros', 'correo']);
  });

  it('todos los hrefs son rutas internas del panel', () => {
    for (const item of deriveChecklist(inputs())) {
      expect(item.href, item.key).toMatch(/^\/(admin|formador)\//);
    }
  });
});

describe('isChecklistComplete', () => {
  it('false con lista vacía (nada que celebrar si no se pudo leer nada)', () => {
    expect(isChecklistComplete([])).toBe(false);
  });

  it('false con al menos un pendiente', () => {
    const items = deriveChecklist(inputs({ smtpStatus: 'none' }));
    expect(isChecklistComplete(items)).toBe(false);
  });

  it('true cuando lo único «pendiente» era un cobros que el admin dijo no querer', () => {
    // 5 ítems hechos + cobros omitido por «No vendo cursos» = academia lista.
    const items = deriveChecklist(inputs({ stripeConfigured: false }));
    expect(isChecklistComplete(items)).toBe(true);
  });
});
